<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('customers')->insert(['id' => 1, 'name' => 'AVENT/AVANOS', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; Yustin.Ramirez@avanos.com; Miguel.Velazquez@avanos.com; Verduzco; Alba.Verduzco@avanos.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; Miguel.Velazquez@avanos.com; Alba.Verduzco@avanos.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 2, 'name' => 'LA ADA DE ACUNA', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPE@GRUPOADUANALECEX.COM; DL015299@hyh.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPE@GRUPOADUANALECEX.COM; DL015299@hyh.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 3, 'name' => 'ICONEX-IPS 1', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; itzel.montoya@iconex.com; christina.seay@iconex.com; marlene.nunez@iconex.com; Hernandez.Ernesto@iconex.com; carolina.perez@iconex.com; elizabeth.bojorquez@iconex.com; eloisa.valenzuela@iconex.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; itzel.montoya@iconex.com; christina.seay@iconex.com; marlene.nunez@iconex.com; Hernandez.Ernesto@iconex.com; carolina.perez@iconex.com; elizabeth.bojorquez@iconex.com; eloisa.valenzuela@iconex.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 4, 'name' => 'BNS- NAI', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; aidam@nai-group.com; jrodriguez@nai-group.com; jabdalat@nai-group.com; illamas@grupoaduanalecex.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; jabdalat@nai-group.com; aayala@nai-group.com; lcovarrubias@nai-group.com; jmedrano@nai-group.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 5, 'name' => 'NWS- NAI', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; illamas@grupoaduanalecex.com; linda.llamas@gamil.com; aayala@nai-group.com; mencinas@nai-group.com; lcovarrubias@nai-group.com; dmoreno@nai-group.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; illamas@grupoaduanalecex.com; jmedrano@nai-group.com; aayala@nai-group.com; mencinas@nai-group.com; lcovarrubias@nai-group.com; AduanasHMO@nai-group.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 6, 'name' => 'SEMCO', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; patricia.vidallana@harcosemco.onmicrosoft.com; felipe.rivadeneyra@harcosemco.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; patricia.vidallana@harcosemco.onmicrosoft.com; felipe.rivadeneyra@harcosemco.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 7, 'name' => 'KIMBERLY CLARK', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; Yazmin.G.Juarez@kcc.com; Karla.I.Felix@kcc.com; Excel.D.Quevedo@kcc.com; leonardo.alarcon@kcc.com; fernanda.munoz@kcc.com; gabriel.moreno@kcc.com; arnulfo.vazquez@kcc.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; Yazmin.G.Juarez@kcc.com; Karla.I.Felix@kcc.com; Excel.D.Quevedo@kcc.com; leonardo.alarcon@kcc.com; fernanda.munoz@kcc.com; gabriel.moreno@kcc.com; arnulfo.vazquez@kcc.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 8, 'name' => 'RFS-NAI', 'emails' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; lcovarrubias@nai-group.com; aayala@nai-group.com; AduanasHMO@nai-group.com; jmedrano@nai-group.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 9, 'name' => 'STANDEX', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 10, 'name' => 'SUBMEX', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 11, 'name' => 'AVENT FDA', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 12, 'name' => 'ADA FDA', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 13, 'name' => 'INBOND KC', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; Yazmin.G.Juarez@kcc.com; Karla.I.Felix@kcc.com; Excel.D.Quevedo@kcc.com; leonardo.alarcon@kcc.com; fernanda.munoz@kcc.com; gabriel.moreno@kcc.com; arnulfo.vazquez@kcc.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; Yazmin.G.Juarez@kcc.com; Karla.I.Felix@kcc.com; Excel.D.Quevedo@kcc.com; leonardo.alarcon@kcc.com; fernanda.munoz@kcc.com; gabriel.moreno@kcc.com; arnulfo.vazquez@kcc.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 14, 'name' => 'NWS-NAI 5', 'emails' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; Ldaniel_moreno@grupoaduanalecex.com; dlopez@grupoaduanalecex.com; ', 'emails_add' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; Ldaniel_moreno@grupoaduanalecex.com; dlopez@grupoaduanalecex.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 18, 'name' => 'TestCustomer', 'emails' => 'jc_jacobo@outlook.com; jakodev@outlook.com; ', 'emails_add' => 'jc_jacobo@outlook.com; jakodev@outlook.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 20, 'name' => 'NWS-NAI 3', 'emails' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; Ldaniel_moreno@grupoaduanalecex.com; dlopez@grupoaduanalecex.com; ', 'emails_add' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; Ldaniel_moreno@grupoaduanalecex.com; dlopez@grupoaduanalecex.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 21, 'name' => 'NAI NOGALES DIST. CENTER', 'emails' => 'operaciones@grupoaduanalecex.com; dlopez@grupoaduanalecex.com; AduanasHMO@nai-group.com; ', 'emails_add' => 'operaciones@grupoaduanalecex.com; dlopez@grupoaduanalecex.com; AduanasHMO@nai-group.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 22, 'name' => 'NWS-NAI 2', 'emails' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; Ldaniel_moreno@grupoaduanalecex.com; dlopez@grupoaduanalecex.com; ', 'emails_add' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; Ldaniel_moreno@grupoaduanalecex.com; dlopez@grupoaduanalecex.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 23, 'name' => 'CLIENTE NO INDENTIFICADO', 'emails' => 'operaciones@grupoaduanalecex.com; ', 'emails_add' => 'operaciones@grupoaduanalecex.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 25, 'name' => 'NWS-NAI 4', 'emails' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 30, 'name' => 'ICONEX-IPS 4', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; itzel.montoya@iconex.com; christina.seay@iconex.com; marlene.nunez@iconex.com; Hernandez.Ernesto@iconex.com; carolina.perez@iconex.com; elizabeth.bojorquez@iconex.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; itzel.montoya@iconex.com; christina.seay@iconex.com; marlene.nunez@iconex.com; Hernandez.Ernesto@iconex.com; carolina.perez@iconex.com; elizabeth.bojorquez@iconex.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 31, 'name' => 'ICONEX-IPS 3', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM,itzel.montoya@iconex.com,christina.seay@iconex.com,marlene.nunez@iconex.com,Hernandez.Ernesto@iconex.com,carolina.perez@iconex.com,elizabeth.bojorquez@iconex.com,eloisa.valenzuela@iconex.com', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM,itzel.montoya@iconex.com,christina.seay@iconex.com,marlene.nunez@iconex.com,Hernandez.Ernesto@iconex.com,carolina.perez@iconex.com,elizabeth.bojorquez@iconex.com,eloisa.valenzuela@iconex.com', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 32, 'name' => 'AVENT 1', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 33, 'name' => 'AVENT 2', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 34, 'name' => 'AVENT 3', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 35, 'name' => 'AVENT 4', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM,aayala@nai-group.com,btrujillo@nai-group.com,mdominguez@nai-group.com,aflores@nai-group.com,cduran@nai-group.com', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 36, 'name' => 'AVENT 5', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM,DLOPEZ@GRUPOADUANALECEX.COM', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 37, 'name' => 'DCO', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM,logistica@dcosupply.com,mariela@dcosupply.com,vi@dcosupply.com', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM,logistica@dcosupply.com,mariela@dcosupply.com,vi@dcosupply.com', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 38, 'name' => 'BD muestra', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM,dlopez@grupoaduanalecex.com', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM,dlopez@grupoaduanalecex.com', 'capacity' => 0 ]);
        //DB::table('customers')->insert(['id' => 39, 'name' => '', 'emails' => '', 'emails_add' => '', 'capacity' => 0 ]);
        //DB::table('customers')->insert(['id' => 40, 'name' => 'semc', 'emails' => '', 'emails_add' => '', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 41, 'name' => 'NAI 1', 'emails' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 42, 'name' => 'Excel Quevedo', 'emails' => 'Excel.D.Quevedo@kcc.com; ', 'emails_add' => 'Excel.D.Quevedo@kcc.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 43, 'name' => 'NAI NWS CAJAS EN CAPIN', 'emails' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; Ldaniel_moreno@grupoaduanalecex.com; dlopez@grupoaduanalecex.com; ', 'emails_add' => 'AduanasHMO@nai-group.com; OPERACIONES@GRUPOADUANALECEX.COM; Ldaniel_moreno@grupoaduanalecex.com; dlopez@grupoaduanalecex.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 44, 'name' => 'BD Sur  (CrBard)', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; Erick.Morales2@bd.com; JoseLuis.Villa@bd.com; carolina.curiel@bd.com; Julio.Duarte@bd.com; Luis.DeLeon@bd.com; Gibran.Joaquin.Vasquez@bd.com; Margarita.Torres@bd.com; Patricia.Lopez@bd.com; Rafael.Fuentes@bd.com; Carlos.Lizarraga@...; ', 'emails_add' => 'Miguel.Luna@bd.com; Gibran.Joaquin.Vasquez@bd.com; Erick.Morales2@bd.com; Julio.Duarte@bd.com; Leopoldo.Avendano@bd.com; Brenda.Losoya@bd.com; Hilario.Coronado@bd.com; Dalia.Rivera@bd.com; roberto.avila2@bd.com; Luis.DeLeon@bd.com; Margarita.Torres@bd.com; Patricia...; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 45, 'name' => 'TestCustomer2', 'emails' => 'jc_jacobo@outlook.com; jc_jacobo@outlook.com; ', 'emails_add' => 'jc_jacobo@outlook.com; jc_jacobo@outlook.com; ', 'capacity' => 0 ]);
        //DB::table('customers')->insert(['id' => 46, 'name' => 'TestCustomer3', 'emails' => 'jc_jacobo@outlook.com; jc_jacobo@outlook.com; ', 'emails_add' => 'jc_jacobo@outlook.com; jc_jacobo@outlook.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 47, 'name' => 'ITT Cannon', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; dlopez@grupoaduanalecex.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; dlopez@grupoaduanalecex.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 48, 'name' => 'INBOND AVENT-AVAST', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; Yustin.Ramirez@avanos.com; Miguel.Velazquez@avanos.com; Verduzco; Alba.Verduzco@avanos.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; Miguel.Velazquez@avanos.com; Alba.Verduzco@avanos.com; ', 'capacity' => 0 ]);
        DB::table('customers')->insert(['id' => 49, 'name' => 'BD FDA', 'emails' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; Luis.DeLeon@bd.com; Cinthya.Soto@bd.com; Manuel.Garcia2@bd.com; Erick.Morales2@bd.com; Julio.Duarte@bd.com; Gibran.Joaquin.Vasquez@bd.com; ', 'emails_add' => 'OPERACIONES@GRUPOADUANALECEX.COM; DLOPEZ@GRUPOADUANALECEX.COM; Luis.DeLeon@bd.com; Cinthya.Soto@bd.com; Manuel.Garcia2@bd.com; ', 'capacity' => 0 ]);        
        
    }
}
