<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert(['type' => 'user', 'name' => 'Juan' , 'email' => 'jakodev@outlook.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => 'del_income,del_outcome,edit_part_number,edit_customer' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Jacobo' , 'email' => 'Jacobo@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '18']);
        
        DB::table('users')->insert(['type' => 'user', 'name' => 'DANIELA.LOPEZ' , 'email' => 'danielalv@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        //DB::table('users')->insert(['type' => 'user', 'name' => 'MITZY.RUIZ' , 'email' => 'MITZY.RUIZ@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'ALONSO.LOPEZ' , 'email' => 'alonso@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => 'del_outcome,edit_part_number' , 'customer_ids' => NULL]);
        //DB::table('users')->insert(['type' => 'user', 'name' => 'ALONSO.LOPEZ' , 'email' => 'alonso@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => 'edit_part_number' , 'customer_ids' => NULL]);

        DB::table('users')->insert(['type' => 'user', 'name' => 'VICTOR.RODRIGUE' , 'email' => 'victor_rodriguez@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => 'del_income,del_outcome' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'ALEJANDRO.SANDO' , 'email' => 'alejandro_sandoval@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => 'edit_part_number' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'LUIS.MENDIVIL' , 'email' => 'LUIS.MENDIVIL@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Manuel.Gutierrez' , 'email' => 'manuel@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => 'del_income,del_outcome' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'MARGARITA.FELIX' , 'email' => 'margarita@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => 'del_income,del_outcome,edit_part_number,edit_customer' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'LUIS.MORENO' , 'email' => 'ldaniel_moreno@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'SONIA.FRANCO' , 'email' => 'SONIA.FRANCO@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Lizbeth.Cox' , 'email' => 'lizbeth_cox@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$8TrX9FO3ya/88LRnp7YiDOg8166jQKmrDm3o2jiFZrfl1Y7hBqdai' , 'permits' => 'del_income,del_outcome,edit_part_number,edit_customer' , 'customer_ids' => NULL]);
         DB::table('users')->insert(['type' => 'user', 'name' => 'KEVIN.ROMERO' , 'email' => 'kevin_romero@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'Christian.Montijo' , 'email' => 'Christian.Montijo@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'Cesar.Aguilar' , 'email' => 'Cesar.Aguilar@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'Michelle.Salazar' , 'email' => 'Michelle.Salazar@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'ADRIAN.GONZALEZ' , 'email' => 'adrian@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => 'del_income,del_outcome,edit_part_number,edit_customer' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'Fernanda.Gomez' , 'email' => 'Fernanda.Gomez@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'Marcela.Pacheco' , 'email' => 'Marcela.Pacheco@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'David.Lopez' , 'email' => 'david@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Emily.Mendivil' , 'email' => 'emily_mendivil@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'Marcela.Vallejo' , 'email' => 'Marcela.Vallejo@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Josue.Alarcon' , 'email' => 'josue_alarcon@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Katia.Flores' , 'email' => 'katia_flores@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'Elsy' , 'email' => 'Elsy@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Jocelynn.murrieta' , 'email' => 'jocelynn_murrieta@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'javier.linares' , 'email' => 'jlinares@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'humberto.meza' , 'email' => 'humberto_meza@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'joseluis.gallo' , 'email' => 'joseluis_gallo@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'javier.gimenez' , 'email' => 'javier.gimenez@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'training' , 'email' => 'training@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'training2' , 'email' => 'training2@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'Francisco.ALvarez' , 'email' => 'Francisco.ALvarez@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        // DB::table('users')->insert(['type' => 'user', 'name' => 'Karelia.Lopez' , 'email' => 'Karelia.Lopez@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Ruby' , 'email' => 'cinthya_rubi@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$uu3a4ibnlvS/fgjiWo3H7OZhHdsoaEIWvnBTxGratmS8tEeqk7pbi' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Alondra.Soto' , 'email' => 'alondra_soto@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Marvin.Caro' , 'email' => 'marvin_caro@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Iber.Montoya' , 'email' => 'iber_montoya@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Gloria.Barcelo' , 'email' => 'gloria@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Geraldine.DelArca' , 'email' => 'geraldine@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);
        DB::table('users')->insert(['type' => 'user', 'name' => 'Paulina.Flores' , 'email' => 'paulina_flores@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$xHQJSabMghHVkS37VBJPbu3V.5rHB2achJq/fiGO6SFGxmFHK6nUK' , 'permits' => '' , 'customer_ids' => NULL]);

        DB::table('users')->insert(['type' => 'customer', 'name' => 'Semco' , 'email' => 'Semco@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '6']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Iconex' , 'email' => 'Iconex@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '3']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'KimberlyClark' , 'email' => 'KimberlyClark@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '7']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Iconex2' , 'email' => 'Iconex2@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '14']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'AAcuna' , 'email' => 'AAcuna@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '2']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Avent' , 'email' => 'Avent@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '1']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'BNSNAI' , 'email' => 'BNSNAI@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '4']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'NWSNAI' , 'email' => 'NWSNAI@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '5']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'RFSNAI' , 'email' => 'RFSNAI@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '8']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Standex' , 'email' => 'Standex@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '9']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Submex' , 'email' => 'Submex@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '10']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'AventFDA' , 'email' => 'AventFDA@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '11']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'AdaFDA' , 'email' => 'AdaFDA@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '12']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'InbondKC' , 'email' => 'InbondKC@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '13']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'test' , 'email' => 'test@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '18']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'NAINDC' , 'email' => 'NAINDC@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '21']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'NAI2' , 'email' => 'NAI2@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '22']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'NAI3' , 'email' => 'NAI3@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '20']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Sonitronies' , 'email' => 'Sonitronies@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '24']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'NAI4' , 'email' => 'NAI4@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '25']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Atronix' , 'email' => 'Atronix@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '29']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'NWS4' , 'email' => 'NWS4@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '25']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'NWS3' , 'email' => 'NWS3@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '20']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Iconex3' , 'email' => 'Iconex3@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '31']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Iconex4' , 'email' => 'Iconex4@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '30']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Avent1' , 'email' => 'Avent1@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '32']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Avent2' , 'email' => 'Avent2@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '33']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Avent3' , 'email' => 'Avent3@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '34']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Avent4' , 'email' => 'Avent4@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '35']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'Avent5' , 'email' => 'Avent5@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '36']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'DCO' , 'email' => 'DCO@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '37']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'BD_1' , 'email' => 'BD_1@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '38']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'NAI1' , 'email' => 'NAI1@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '41']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'materiales' , 'email' => 'materiales@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '44']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'MRO' , 'email' => 'MRO@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '44']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'BD' , 'email' => 'BD@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '44']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'ITTCannon' , 'email' => 'ITTCannon@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '47']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'BDFDA' , 'email' => 'BDFDA@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '49']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'NAICAPIN' , 'email' => 'NAICAPIN@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '43']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'notest' , 'email' => 'notest@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '18']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'BD_COMPRADOR' , 'email' => 'BD_COMPRADOR@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => '' , 'customer_ids' => '44']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'CIMSA' , 'email' => 'CIMSA@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => '' , 'customer_ids' => '51']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'CHAMBERLAIN' , 'email' => 'CHAMBERLAIN@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => '' , 'customer_ids' => '52']);
        DB::table('users')->insert(['type' => 'customer', 'name' => 'KCconsultas' , 'email' => 'KC@grupoaduanalecex.com' , 'email_verified_at' => NULL , 'password' => '$2y$10$Pf05.rmwei/neBzcCn/.SueO5MZ3FJzqXtf/ZJmxlTx20Ni3rPv2q' , 'permits' => 'create_oc,quit_onhold' , 'customer_ids' => '7']);

    }
}
